### ISSUE TITLE
Missing Credit?

### ISSUE THREAD

**Issue by HicalebiH** [Kingminer7/BetterQuests#1]
Hi there! 
I’m HicalebiH! Quite a while ago I posted about a mod idea in the GD Modding Discord, and this is basically identical to my idea with only minor differences.
![IMG_1497](https://github.com/user-attachments/assets/59b3ec14-69ed-4b4b-929a-aa74b508a9d2)

Again just asking for credit for the idea, nothing crazy.

Thanks in advanced and hope you’re having a good day!

**Comment by Kingminer7** [comment]
> Hi there! I’m HicalebiH! Quite a while ago I posted about a mod idea in the GD Modding Discord, and this is basically identical to my idea with only minor differences. ![IMG_1497](https://private-user-images.githubusercontent.com/68748871/391298781-59b3ec14-69ed-4b4b-929a-aa74b508a9d2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzk2MDUsIm5iZiI6MTczMzA3OTMwNSwicGF0aCI6Ii82ODc0ODg3MS8zOTEyOTg3ODEtNTliM2VjMTQtNjllZC00YjRiLTkyOWEtYWE3NGI1MDhhOWQyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxODU1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmNiMmFmZjhjODc2MmY3MGJkNDAwMjZiYzI5Y2NhYzJkZTdlNjhkYzNjOTI3ZmMxYmI4ZGRjYzNkNjE1YzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VithPmsp3pU2O_F0Mp-wQeto4xx6U1_Rfafg7BRjC9A)
> 
> Again just asking for credit for the idea, nothing crazy.
> 
> Thanks in advanced and hope you’re having a good day!

shoot yeah ill do that
i meant to do that but completely forgot upon release
sorry bout that!

**Comment by HicalebiH** [comment]
Thank you!
